-- AlterTable
ALTER TABLE "AcademicCalendar" ADD COLUMN     "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "isTermExam" BOOLEAN NOT NULL DEFAULT false;

-- CreateIndex
CREATE INDEX "AcademicCalendar_batchId_idx" ON "AcademicCalendar"("batchId");
