version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: mis
    restart: unless-stopped
    environment:
      POSTGRES_USER: mislms
      POSTGRES_PASSWORD: Number123
      POSTGRES_DB: misdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
