// components/classroom/AcademicCalendar3D.jsx
'use client';

import { useState, useEffect, useCallback, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  X,
  CalendarDays,
  ChevronLeft,
  ChevronRight,
  Plus,
  Save,
  Loader2,
  CheckCircle,
  AlertCircle,
  Info,
  Edit2,
  Trash2,
  FileText,
  Printer,
  Calendar,
  Play,
  StopCircle,
  Sun,
  BookOpen,
  FileCheck,
  Award,
  Users,
  Circle,
  Globe,
  AlertTriangle,
} from 'lucide-react';

const MONTHS = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];
const DAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

const formatDateKey = (date) =>
  `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(
    2,
    '0'
  )}-${String(date.getDate()).padStart(2, '0')}`;
const formatDisplayDate = (date) =>
  new Date(date).toLocaleDateString('en-US', {
    weekday: 'long',
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  });
const formatShortDate = (date) =>
  new Date(date).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
  });
const isWeekend = (date) => [0, 6].includes(new Date(date).getDay());
const addDays = (date, days) => {
  const r = new Date(date);
  r.setDate(r.getDate() + days);
  return r;
};
const addWeeks = (date, weeks) => addDays(date, weeks * 7);
const getMonday = (date) => {
  const d = new Date(date);
  d.setDate(d.getDate() - ((d.getDay() + 6) % 7));
  return d;
};

// Helper: check if an event is a weekend holiday that should be hidden
const isWeekendHoliday = (event) => {
  if (event.eventType !== 'holiday') return false;
  const desc = (event.description || '').toLowerCase();
  // Check for weekend-related descriptions
  if (
    desc.includes('weekend') ||
    desc.includes('saturday') ||
    desc.includes('sunday')
  )
    return true;
  // Check if date falls on weekend AND it's auto-generated
  if (event.isAutoGenerated && isWeekend(new Date(event.date))) return true;
  return false;
};

const EVENT_TYPES = [
  {
    value: 'semester_start',
    label: 'Semester Start',
    color: 'from-green-500 to-emerald-600',
    Icon: Play,
    bgColor: 'bg-green-100',
    textColor: 'text-green-800',
    shortLabel: 'Sem Start',
  },
  {
    value: 'semester_end',
    label: 'Semester End',
    color: 'from-red-500 to-rose-600',
    Icon: StopCircle,
    bgColor: 'bg-red-100',
    textColor: 'text-red-800',
    shortLabel: 'Sem End',
  },
  {
    value: 'holiday',
    label: 'Holiday',
    color: 'from-orange-500 to-amber-600',
    Icon: Sun,
    bgColor: 'bg-orange-100',
    textColor: 'text-orange-800',
    shortLabel: 'Holiday',
  },
  {
    value: 'first_term_start',
    label: 'First Term',
    color: 'from-blue-500 to-cyan-600',
    Icon: BookOpen,
    bgColor: 'bg-blue-100',
    textColor: 'text-blue-800',
    shortLabel: 'Term 1',
  },
  {
    value: 'second_term_start',
    label: 'Second Term',
    color: 'from-indigo-500 to-blue-600',
    Icon: BookOpen,
    bgColor: 'bg-indigo-100',
    textColor: 'text-indigo-800',
    shortLabel: 'Term 2',
  },
  {
    value: 'exam_start',
    label: 'Terminal Exam',
    color: 'from-purple-500 to-violet-600',
    Icon: FileText,
    bgColor: 'bg-purple-100',
    textColor: 'text-purple-800',
    shortLabel: 'Exam',
  },
  {
    value: 'exam_end',
    label: 'Exam End',
    color: 'from-violet-500 to-purple-600',
    Icon: FileCheck,
    bgColor: 'bg-violet-100',
    textColor: 'text-violet-800',
    shortLabel: 'Exam End',
  },
  {
    value: 'result_publication',
    label: 'Results',
    color: 'from-pink-500 to-rose-600',
    Icon: Award,
    bgColor: 'bg-pink-100',
    textColor: 'text-pink-800',
    shortLabel: 'Results',
  },
  {
    value: 'meeting',
    label: 'Meeting',
    color: 'from-gray-500 to-slate-600',
    Icon: Users,
    bgColor: 'bg-gray-100',
    textColor: 'text-gray-800',
    shortLabel: 'Meeting',
  },
  {
    value: 'other',
    label: 'Other',
    color: 'from-teal-500 to-cyan-600',
    Icon: Circle,
    bgColor: 'bg-teal-100',
    textColor: 'text-teal-800',
    shortLabel: 'Other',
  },
];

export default function AcademicCalendar3D({
  classroomId,
  batchId,
  isOpen,
  onClose,
}) {
  const today = new Date();
  const [currentDate, setCurrentDate] = useState(
    new Date(today.getFullYear(), today.getMonth(), 1)
  );
  const [selectedDate, setSelectedDate] = useState(null);
  const [events, setEvents] = useState({});
  const [viewMode, setViewMode] = useState('calendar');
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [showEventModal, setShowEventModal] = useState(false);
  const [successMessage, setSuccessMessage] = useState(null);
  const [errorMessage, setErrorMessage] = useState(null);
  const [autoGenerating, setAutoGenerating] = useState(false);
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);
  const [deleteTargetId, setDeleteTargetId] = useState(null);
  const [deleteTargetType, setDeleteTargetType] = useState(null);
  const printRef = useRef(null);

  const [batchInfo, setBatchInfo] = useState(null);
  const [allEvents, setAllEvents] = useState([]);
  const [semesterStartDate, setSemesterStartDate] = useState(null);
  const [semesterEndDate, setSemesterEndDate] = useState(null);
  const [dataLoaded, setDataLoaded] = useState(false);

  const isGlobalCalendar = !batchId;
  const isBatchCalendar = !!batchId;
  const currentYear = currentDate.getFullYear();
  const currentMonth = currentDate.getMonth();

  const [eventForm, setEventForm] = useState({
    id: null,
    date: '',
    eventType: 'other',
    description: '',
    batchId: batchId || '',
  });

  const fetchBatchInfo = useCallback(async () => {
    if (!batchId) {
      setDataLoaded(true);
      return;
    }
    try {
      const r = await fetch(`/api/batches/${batchId}`);
      if (r.ok) {
        const d = await r.json();
        setBatchInfo(d.batch || d);
      } else setBatchInfo({ name: 'Batch #' + batchId });
    } catch {
      setBatchInfo({ name: 'Batch #' + batchId });
    }
  }, [batchId]);

  const fetchAllEvents = useCallback(async () => {
    try {
      const [bR, gR] = await Promise.all([
        isBatchCalendar
          ? fetch(`/api/academic-calendar?batchId=${batchId}`)
          : null,
        fetch('/api/academic-calendar'),
      ]);
      let bE = [],
        gE = [];
      if (bR?.ok) bE = (await bR.json()).events || [];
      if (gR.ok)
        gE = ((await gR.json()).events || []).filter((e) => !e.batchId);
      const map = new Map();
      [...bE, ...gE].forEach((e) => {
        const k = `${formatDateKey(new Date(e.date))}-${e.eventType}`;
        if (!map.has(k) || (e.batchId && !map.get(k).batchId)) map.set(k, e);
      });
      const merged = Array.from(map.values());
      setAllEvents(merged);
      const ss = merged.find((e) => e.eventType === 'semester_start');
      const se = merged.find((e) => e.eventType === 'semester_end');
      if (ss) setSemesterStartDate(new Date(ss.date));
      if (se) setSemesterEndDate(new Date(se.date));
      return merged;
    } catch {
      return [];
    }
  }, [batchId, isBatchCalendar]);

  useEffect(() => {
    if (isOpen) {
      setDataLoaded(false);
      setLoading(true);
      fetchBatchInfo();
    }
  }, [isOpen, fetchBatchInfo]);
  useEffect(() => {
    if (batchInfo !== null) {
      (async () => {
        await fetchAllEvents();
        setDataLoaded(true);
      })();
    }
  }, [batchInfo, fetchAllEvents]);

  const autoGenerateSemesterDates = useCallback(
    async (semesterStartEvent) => {
      if (!batchId || !semesterStartEvent) return;
      setAutoGenerating(true);
      try {
        const startDate = new Date(semesterStartEvent.date);
        const semesterEndDate = addWeeks(startDate, 16);
        const term1Monday = getMonday(addWeeks(startDate, 7));
        const term2Monday = getMonday(addWeeks(startDate, 12));

        const eventsToCreate = [
          {
            date: formatDateKey(semesterEndDate),
            eventType: 'semester_end',
            description: 'Semester End (Week 16)',
            batchId: parseInt(batchId),
            isAutoGenerated: true,
          },
          {
            date: formatDateKey(term1Monday),
            eventType: 'first_term_start',
            description: 'First Term Exam Week (Week 7)',
            batchId: parseInt(batchId),
            isAutoGenerated: true,
          },
          {
            date: formatDateKey(term2Monday),
            eventType: 'second_term_start',
            description: 'Second Term Exam Week (Week 12)',
            batchId: parseInt(batchId),
            isAutoGenerated: true,
          },
        ];

        for (let i = 0; i < 5; i++) {
          eventsToCreate.push({
            date: formatDateKey(addDays(term1Monday, i)),
            eventType: 'exam_start',
            description: `First Term Terminal Exam - Day ${i + 1}`,
            batchId: parseInt(batchId),
            isAutoGenerated: true,
            isTermExam: true,
          });
          eventsToCreate.push({
            date: formatDateKey(addDays(term2Monday, i)),
            eventType: 'exam_start',
            description: `Second Term Terminal Exam - Day ${i + 1}`,
            batchId: parseInt(batchId),
            isAutoGenerated: true,
            isTermExam: true,
          });
        }

        await Promise.all(
          eventsToCreate.map((body) =>
            fetch('/api/academic-calendar', {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify(body),
            })
          )
        );
      } catch (e) {
        console.error('Auto-gen error:', e);
      } finally {
        setAutoGenerating(false);
      }
    },
    [batchId]
  );

  const fetchEvents = useCallback(async () => {
    try {
      const monthStart = new Date(currentYear, currentMonth, 1);
      const monthEnd = new Date(currentYear, currentMonth + 1, 0);
      let apiEvents = [];
      if (isBatchCalendar) {
        const [bR, gR] = await Promise.all([
          fetch(
            `/api/academic-calendar?startDate=${formatDateKey(
              monthStart
            )}&endDate=${formatDateKey(monthEnd)}&batchId=${batchId}`
          ),
          fetch(
            `/api/academic-calendar?startDate=${formatDateKey(
              monthStart
            )}&endDate=${formatDateKey(monthEnd)}`
          ),
        ]);
        const bD = bR.ok ? (await bR.json()).events || [] : [];
        const gD = gR.ok
          ? ((await gR.json()).events || []).filter((e) => !e.batchId)
          : [];
        const map = new Map();
        [...bD, ...gD].forEach((e) => {
          const k = `${formatDateKey(new Date(e.date))}-${e.eventType}`;
          if (!map.has(k) || (e.batchId && !map.get(k).batchId)) map.set(k, e);
        });
        apiEvents = Array.from(map.values());
      } else {
        const r = await fetch(
          `/api/academic-calendar?startDate=${formatDateKey(
            monthStart
          )}&endDate=${formatDateKey(monthEnd)}`
        );
        if (r.ok)
          apiEvents = ((await r.json()).events || []).filter((e) => !e.batchId);
      }
      const em = {};
      apiEvents.forEach((e) => {
        const dk = formatDateKey(new Date(e.date));
        if (!em[dk]) em[dk] = [];
        em[dk].push(e);
      });
      setEvents(em);
    } catch (e) {
      console.error('Error:', e);
    } finally {
      setLoading(false);
    }
  }, [currentYear, currentMonth, batchId, isGlobalCalendar, isBatchCalendar]);

  useEffect(() => {
    if (isOpen && dataLoaded) {
      setLoading(true);
      fetchEvents();
    }
  }, [isOpen, dataLoaded, fetchEvents]);

  // ==================== SEMESTER CALENDAR MONTHS - HIDE ALL WEEKEND HOLIDAYS ====================
  const getCalendarMonths = useCallback(() => {
    if (!semesterStartDate) return [];
    const start = new Date(
      semesterStartDate.getFullYear(),
      semesterStartDate.getMonth(),
      1
    );
    const end = semesterEndDate
      ? new Date(semesterEndDate.getFullYear(), semesterEndDate.getMonth(), 1)
      : new Date(
          semesterStartDate.getFullYear(),
          semesterStartDate.getMonth() + 6,
          1
        );

    const months = [];
    let current = new Date(start);
    while (current <= end) {
      const year = current.getFullYear();
      const month = current.getMonth();
      const daysInMonth = new Date(year, month + 1, 0).getDate();
      const firstDay = new Date(year, month, 1).getDay();

      // Get events for this month - HIDE ALL WEEKEND HOLIDAYS
      const monthEvents = allEvents
        .filter((e) => {
          const ed = new Date(e.date);
          return ed.getFullYear() === year && ed.getMonth() === month;
        })
        .filter((e) => !isWeekendHoliday(e)) // <-- Hides all weekend holidays
        .sort((a, b) => new Date(a.date) - new Date(b.date));

      months.push({
        year,
        month,
        monthName: MONTHS[month],
        daysInMonth,
        firstDay,
        events: monthEvents,
        isCurrentMonth:
          year === today.getFullYear() && month === today.getMonth(),
      });

      current.setMonth(current.getMonth() + 1);
    }
    return months;
  }, [semesterStartDate, semesterEndDate, allEvents, today]);

  const prevMonth = () =>
    setCurrentDate(new Date(currentYear, currentMonth - 1, 1));
  const nextMonth = () =>
    setCurrentDate(new Date(currentYear, currentMonth + 1, 1));
  const goToToday = () =>
    setCurrentDate(new Date(today.getFullYear(), today.getMonth(), 1));

  const daysInMonth = new Date(currentYear, currentMonth + 1, 0).getDate();
  const firstDayOfWeek = new Date(currentYear, currentMonth, 1).getDay();

  const handleDateClick = (day) =>
    setSelectedDate(formatDateKey(new Date(currentYear, currentMonth, day)));
  const handleDateDoubleClick = (day) => {
    const dk = formatDateKey(new Date(currentYear, currentMonth, day));
    setSelectedDate(dk);
    setEventForm({
      id: null,
      date: dk,
      eventType: 'other',
      description: '',
      batchId: batchId || '',
    });
    setShowEventModal(true);
  };

  const getEventsForDate = (day) =>
    events[formatDateKey(new Date(currentYear, currentMonth, day))] || [];
  const getEventTypeDetails = (et) =>
    EVENT_TYPES.find((e) => e.value === et) || EVENT_TYPES[9];
  const selectedDateEvents = selectedDate ? events[selectedDate] || [] : [];

  const handleSaveEvent = async () => {
    if (!eventForm.description.trim()) {
      setErrorMessage('Enter description');
      setTimeout(() => setErrorMessage(null), 3000);
      return;
    }
    setSaving(true);
    try {
      const body = {
        ...eventForm,
        date: eventForm.date,
        batchId: isGlobalCalendar ? null : batchId ? parseInt(batchId) : null,
      };
      const res = await fetch('/api/academic-calendar', {
        method: eventForm.id ? 'PUT' : 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(
          eventForm.id ? { ...body, id: eventForm.id } : body
        ),
      });
      if (!res.ok) throw new Error((await res.json()).error);
      setShowEventModal(false);
      const saved = await res.json();
      const savedData = saved.event || saved;

      if (
        !eventForm.id &&
        eventForm.eventType === 'semester_start' &&
        isBatchCalendar &&
        savedData
      ) {
        setSuccessMessage('Auto-generating semester schedule...');
        setTimeout(() => setSuccessMessage(null), 3000);
        await autoGenerateSemesterDates(savedData);
        await fetchAllEvents();
        fetchEvents();
        setSuccessMessage(
          'Semester End, First Term & Second Term exams generated!'
        );
        setTimeout(() => setSuccessMessage(null), 3000);
        setSaving(false);
        return;
      }
      setSuccessMessage(eventForm.id ? 'Updated!' : 'Created!');
      setTimeout(() => setSuccessMessage(null), 3000);
      await fetchAllEvents();
      fetchEvents();
    } catch (e) {
      setErrorMessage(e.message);
      setTimeout(() => setErrorMessage(null), 3000);
    } finally {
      setSaving(false);
    }
  };

  const handleEditEvent = (event) => {
    setEventForm({
      id: event.id,
      date: formatDateKey(new Date(event.date)),
      eventType: event.eventType,
      description: event.description,
      batchId: event.batchId || batchId || '',
    });
    setShowEventModal(true);
  };

  const handleDeleteEvent = (id) => {
    const event = allEvents.find((e) => e.id === id);
    setDeleteTargetId(id);
    setDeleteTargetType(
      event?.eventType === 'semester_start' && isBatchCalendar
        ? 'semester_start'
        : 'single'
    );
    setShowDeleteConfirm(true);
  };

  const confirmDelete = async () => {
    setShowDeleteConfirm(false);
    if (!deleteTargetId) return;
    try {
      if (deleteTargetType === 'semester_start') {
        const autoEvents = allEvents.filter(
          (e) => e.isAutoGenerated && e.batchId === parseInt(batchId)
        );
        await Promise.all(
          autoEvents.map((e) =>
            fetch(`/api/academic-calendar?id=${e.id}`, { method: 'DELETE' })
          )
        );
        await fetch(`/api/academic-calendar?id=${deleteTargetId}`, {
          method: 'DELETE',
        });
        setSuccessMessage(
          `Deleted Semester Start & ${autoEvents.length} events!`
        );
        setTimeout(() => setSuccessMessage(null), 3000);
      } else {
        await fetch(`/api/academic-calendar?id=${deleteTargetId}`, {
          method: 'DELETE',
        });
        setSuccessMessage('Event deleted!');
        setTimeout(() => setSuccessMessage(null), 3000);
      }
      await fetchAllEvents();
      fetchEvents();
    } catch (e) {
      setErrorMessage('Failed to delete');
      setTimeout(() => setErrorMessage(null), 3000);
    }
    setDeleteTargetId(null);
    setDeleteTargetType(null);
  };

  const handlePrint = () => window.print();
  if (!isOpen) return null;

  const calendarMonthsList = getCalendarMonths();

  return (
    <div className="fixed inset-0 z-50 overflow-hidden">
      <div className="absolute inset-0 bg-black/50" onClick={onClose} />
      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        exit={{ opacity: 0, scale: 0.95 }}
        className="absolute inset-4 md:inset-8 bg-white rounded-2xl shadow-2xl flex flex-col overflow-hidden"
      >
        <div
          className={`px-6 py-4 flex items-center justify-between flex-shrink-0 print:hidden ${
            isGlobalCalendar
              ? 'bg-gradient-to-r from-slate-700 via-slate-600 to-slate-700'
              : 'bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-600'
          }`}
        >
          <div className="flex items-center gap-4">
            <button
              onClick={onClose}
              className="text-white/80 hover:text-white p-2"
            >
              <X size={20} />
            </button>
            <div>
              <h2 className="text-xl font-bold text-white">
                <CalendarDays size={24} className="inline mr-2" />
                Academic Calendar {currentYear}
              </h2>
              <p className="text-white/70 text-sm">
                {batchInfo
                  ? `Batch: ${batchInfo.name}${
                      batchInfo.department
                        ? ` (${batchInfo.department.name})`
                        : ''
                    }`
                  : isGlobalCalendar
                  ? 'Global Calendar'
                  : 'Loading...'}
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <div className="bg-white/10 rounded-lg p-1 flex">
              <button
                onClick={() => setViewMode('calendar')}
                className={`px-3 py-1.5 rounded-md text-sm font-medium ${
                  viewMode === 'calendar'
                    ? 'bg-white text-indigo-600'
                    : 'text-white/70'
                }`}
              >
                Month
              </button>
              {isBatchCalendar && (
                <button
                  onClick={() => setViewMode('report')}
                  className={`px-3 py-1.5 rounded-md text-sm font-medium ${
                    viewMode === 'report'
                      ? 'bg-white text-indigo-600'
                      : 'text-white/70'
                  }`}
                >
                  Semester View
                </button>
              )}
            </div>
            <button
              onClick={handlePrint}
              className="px-3 py-1.5 bg-white/20 text-white rounded-lg text-sm flex items-center gap-1"
            >
              <Printer size={14} /> Print
            </button>
          </div>
        </div>

        <div className="hidden print:block text-center py-2 border-b-2 border-gray-700 px-6">
          <h1 className="text-lg font-bold text-gray-900">
            Asian College of Higher Studies
          </h1>
          {batchInfo && (
            <p className="text-sm font-semibold text-gray-700">
              {batchInfo.name}
              {batchInfo.department?.name && ` - ${batchInfo.department.name}`}
            </p>
          )}
          <h2 className="text-base font-bold text-gray-800">
            Academic Calendar {currentYear}
          </h2>
          <p className="text-xs text-gray-600">
            Semester:{' '}
            {semesterStartDate ? formatShortDate(semesterStartDate) : 'N/A'} -{' '}
            {semesterEndDate ? formatShortDate(semesterEndDate) : 'N/A'}
          </p>
        </div>

        <AnimatePresence>
          {successMessage && (
            <motion.div
              initial={{ opacity: 0, y: -20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="absolute top-20 right-6 z-50 bg-green-50 border-l-4 border-green-500 text-green-800 px-4 py-3 rounded-lg shadow-lg print:hidden"
            >
              <CheckCircle size={18} className="inline mr-2" />
              {successMessage}
            </motion.div>
          )}
          {errorMessage && (
            <motion.div
              initial={{ opacity: 0, y: -20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="absolute top-20 right-6 z-50 bg-red-50 border-l-4 border-red-500 text-red-800 px-4 py-3 rounded-lg shadow-lg print:hidden"
            >
              <AlertCircle size={18} className="inline mr-2" />
              {errorMessage}
            </motion.div>
          )}
        </AnimatePresence>

        {showDeleteConfirm && (
          <div className="fixed inset-0 z-[70] flex items-center justify-center">
            <div
              className="fixed inset-0 bg-black/50"
              onClick={() => {
                setShowDeleteConfirm(false);
                setDeleteTargetId(null);
              }}
            />
            <motion.div
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              className="relative bg-white rounded-2xl shadow-xl max-w-md w-full p-6 mx-4"
            >
              <div className="flex items-center justify-center mb-4">
                <div className="w-16 h-16 bg-red-100 rounded-full flex items-center justify-center">
                  <AlertTriangle size={32} className="text-red-600" />
                </div>
              </div>
              <h3 className="text-xl font-bold text-center text-gray-800 mb-2">
                {deleteTargetType === 'semester_start'
                  ? 'Delete All Semester Events?'
                  : 'Delete Event?'}
              </h3>
              <p className="text-gray-600 text-center mb-6">
                {deleteTargetType === 'semester_start'
                  ? 'This will delete Semester Start and ALL auto-generated events (18 total).'
                  : 'This cannot be undone.'}
              </p>
              <div className="flex gap-3">
                <button
                  onClick={() => {
                    setShowDeleteConfirm(false);
                    setDeleteTargetId(null);
                  }}
                  className="flex-1 px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50"
                >
                  Cancel
                </button>
                <button
                  onClick={confirmDelete}
                  className="flex-1 px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 flex items-center justify-center gap-2"
                >
                  <Trash2 size={18} />
                  Delete
                </button>
              </div>
            </motion.div>
          </div>
        )}

        {autoGenerating && (
          <div className="absolute inset-0 bg-white/80 z-40 flex items-center justify-center">
            <div className="text-center">
              <Loader2
                size={48}
                className="animate-spin text-indigo-600 mx-auto mb-4"
              />
              <p className="text-gray-700 font-medium">
                Auto-generating schedule...
              </p>
            </div>
          </div>
        )}

        {loading ? (
          <div className="flex-1 flex items-center justify-center">
            <div className="text-center">
              <Loader2
                size={48}
                className="animate-spin text-indigo-600 mx-auto mb-4"
              />
              <p className="text-gray-500">Loading...</p>
            </div>
          </div>
        ) : viewMode === 'report' && isBatchCalendar ? (
          /* SEMESTER VIEW */
          <div ref={printRef} className="flex-1 overflow-y-auto p-4">
            <div className="bg-indigo-50 border border-indigo-200 rounded-lg p-3 mb-4 print:bg-gray-100 print:border-gray-300 print:p-2">
              <div className="flex flex-wrap gap-3 text-xs">
                <div>
                  <span className="text-gray-600">Batch:</span>{' '}
                  <span className="font-semibold">
                    {batchInfo?.name || 'N/A'}
                  </span>
                </div>
                <div>
                  <span className="text-gray-600">Start:</span>{' '}
                  <span className="font-semibold text-green-600">
                    {semesterStartDate
                      ? formatShortDate(semesterStartDate)
                      : 'N/A'}
                  </span>
                </div>
                <div>
                  <span className="text-gray-600">End:</span>{' '}
                  <span className="font-semibold text-red-600">
                    {semesterEndDate ? formatShortDate(semesterEndDate) : 'N/A'}
                  </span>
                </div>
              </div>
            </div>

            {calendarMonthsList.length === 0 ? (
              <div className="text-center py-12">
                <Info size={48} className="text-gray-300 mx-auto mb-4" />
                <p className="text-gray-500">Add Semester Start first.</p>
              </div>
            ) : (
              <div className="space-y-2 print:space-y-0">
                {calendarMonthsList.map((month, mIdx) => (
                  <div
                    key={mIdx}
                    className={`print-page bg-white border rounded-lg shadow-sm overflow-hidden print:shadow-none print:border-gray-400 ${
                      month.isCurrentMonth ? 'ring-2 ring-indigo-500' : ''
                    }`}
                  >
                    <div
                      className={`px-3 py-1.5 flex items-center justify-between ${
                        month.isCurrentMonth
                          ? 'bg-indigo-500 text-white'
                          : 'bg-gradient-to-r from-indigo-500 to-purple-500 text-white'
                      } print:bg-gray-200 print:text-black print:py-1`}
                    >
                      <h3 className="text-base font-bold print:text-sm">
                        {month.monthName} {month.year}
                      </h3>
                      <span className="text-xs opacity-80">
                        {month.events.length} event
                        {month.events.length !== 1 ? 's' : ''}
                      </span>
                    </div>
                    <div className="flex">
                      <div className="w-[45%] p-2 border-r print:border-r-gray-300 print:p-1">
                        <div className="grid grid-cols-7 gap-px mb-px">
                          {DAYS.map((d, i) => (
                            <div
                              key={d}
                              className={`text-center text-[7px] font-semibold py-0.5 print:text-[6px] ${
                                i === 0 || i === 6
                                  ? 'text-gray-400'
                                  : 'text-gray-500'
                              }`}
                            >
                              {d.substring(0, 2)}
                            </div>
                          ))}
                        </div>
                        <div className="grid grid-cols-7 gap-px">
                          {Array.from({ length: month.firstDay }).map(
                            (_, i) => (
                              <div
                                key={`e-${i}`}
                                className="min-h-[24px] print:min-h-[20px]"
                              />
                            )
                          )}
                          {Array.from({ length: month.daysInMonth }).map(
                            (_, i) => {
                              const day = i + 1;
                              const dateObj = new Date(
                                month.year,
                                month.month,
                                day
                              );
                              const dateKey = formatDateKey(dateObj);
                              const dayEvents = allEvents
                                .filter(
                                  (e) =>
                                    formatDateKey(new Date(e.date)) === dateKey
                                )
                                .filter((e) => !isWeekendHoliday(e));
                              const hasExam = dayEvents.some(
                                (e) => e.eventType === 'exam_start'
                              );
                              const hasHoliday = dayEvents.some(
                                (e) =>
                                  e.eventType === 'holiday' &&
                                  !e.isAutoGenerated
                              );
                              const isSemStart = dayEvents.some(
                                (e) => e.eventType === 'semester_start'
                              );
                              const isSemEnd = dayEvents.some(
                                (e) => e.eventType === 'semester_end'
                              );
                              const isTerm = dayEvents.some(
                                (e) =>
                                  e.eventType === 'first_term_start' ||
                                  e.eventType === 'second_term_start'
                              );
                              const hasEvent = dayEvents.length > 0;
                              const isSat = dateObj.getDay() === 6;
                              const isSun = dateObj.getDay() === 0;
                              return (
                                <div
                                  key={day}
                                  className={`min-h-[24px] text-center rounded-sm text-[7px] print:min-h-[20px] print:text-[6px] ${
                                    isSemStart
                                      ? 'bg-green-200 text-green-800 font-bold'
                                      : isSemEnd
                                      ? 'bg-red-200 text-red-800 font-bold'
                                      : hasExam
                                      ? 'bg-purple-200 text-purple-800 font-bold'
                                      : isTerm
                                      ? 'bg-blue-200 text-blue-800 font-semibold'
                                      : hasHoliday
                                      ? 'bg-orange-100 text-orange-700'
                                      : isSat || isSun
                                      ? 'bg-white text-gray-400'
                                      : 'bg-white text-gray-700'
                                  } ${
                                    hasEvent
                                      ? 'ring-1 ring-indigo-300'
                                      : 'border border-gray-100'
                                  }`}
                                >
                                  <div>{day}</div>
                                  {hasExam && (
                                    <div className="text-[5px] leading-none">
                                      📝
                                    </div>
                                  )}
                                  {hasHoliday && !hasExam && (
                                    <div className="text-[5px] leading-none">
                                      🏖
                                    </div>
                                  )}
                                </div>
                              );
                            }
                          )}
                        </div>
                      </div>
                      <div className="w-[55%] p-2 print:p-1">
                        <h4 className="text-[9px] font-semibold text-gray-600 uppercase mb-1 print:text-[8px]">
                          Events
                        </h4>
                        {month.events.length === 0 ? (
                          <p className="text-[9px] text-gray-400 italic">
                            No events
                          </p>
                        ) : (
                          <div className="space-y-0.5 max-h-[200px] overflow-y-auto print:max-h-none">
                            {month.events.map((event, ei) => {
                              const et = getEventTypeDetails(event.eventType);
                              const ed = new Date(event.date);
                              return (
                                <div
                                  key={ei}
                                  className="text-[8px] py-0.5 print:text-[7px] border-b border-gray-100 last:border-b-0"
                                >
                                  <span className="font-bold text-gray-700">
                                    {ed.getDate()}{' '}
                                    {MONTHS[ed.getMonth()].substring(0, 3)}
                                  </span>
                                  <span className="text-gray-400"> - </span>
                                  <span
                                    className={`font-medium ${et.textColor}`}
                                  >
                                    {et.shortLabel}
                                  </span>
                                  <span className="text-gray-400">: </span>
                                  <span className="text-gray-600">
                                    {event.description}
                                  </span>
                                  {event.isAutoGenerated && (
                                    <span className="text-[6px] bg-amber-100 text-amber-600 px-1 rounded ml-1">
                                      Auto
                                    </span>
                                  )}
                                </div>
                              );
                            })}
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        ) : (
          /* MONTH VIEW */
          <div className="flex-1 flex overflow-hidden">
            <div className="flex-1 overflow-y-auto p-4">
              <div className="flex items-center justify-between mb-4 flex-wrap gap-2">
                <div className="flex items-center gap-4">
                  <button
                    onClick={prevMonth}
                    className="p-2 hover:bg-gray-100 rounded-lg"
                  >
                    <ChevronLeft size={20} />
                  </button>
                  <h3 className="text-xl font-bold text-gray-900">
                    {MONTHS[currentMonth]} {currentYear}
                  </h3>
                  <button
                    onClick={nextMonth}
                    className="p-2 hover:bg-gray-100 rounded-lg"
                  >
                    <ChevronRight size={20} />
                  </button>
                </div>
                <div className="flex gap-2">
                  <button
                    onClick={goToToday}
                    className="px-4 py-2 text-sm bg-indigo-600 text-white rounded-lg flex items-center gap-1"
                  >
                    <Calendar size={14} /> Today
                  </button>
                  <button
                    onClick={() => {
                      const dk = formatDateKey(today);
                      setSelectedDate(dk);
                      setEventForm({
                        id: null,
                        date: dk,
                        eventType: 'other',
                        description: '',
                        batchId: batchId || '',
                      });
                      setShowEventModal(true);
                    }}
                    className="px-4 py-2 text-sm bg-green-600 text-white rounded-lg flex items-center gap-1"
                  >
                    <Plus size={14} /> Add
                  </button>
                </div>
              </div>
              <div className="grid grid-cols-7 mb-1">
                {DAYS.map((d, i) => (
                  <div
                    key={d}
                    className={`px-1 py-2 text-center text-xs font-semibold uppercase border-y ${
                      i === 0 || i === 6 ? 'bg-gray-100' : 'bg-gray-50'
                    } text-gray-500`}
                  >
                    {d}
                  </div>
                ))}
              </div>
              <div className="grid grid-cols-7 gap-1">
                {Array.from({ length: firstDayOfWeek }).map((_, i) => (
                  <div
                    key={`e-${i}`}
                    className="min-h-[100px] bg-gray-50/30 rounded-lg"
                  />
                ))}
                {Array.from({ length: daysInMonth }).map((_, i) => {
                  const day = i + 1;
                  const dateObj = new Date(currentYear, currentMonth, day);
                  const dayEvents = getEventsForDate(day);
                  const isSelected = selectedDate === formatDateKey(dateObj);
                  const isToday =
                    formatDateKey(dateObj) === formatDateKey(today);
                  const isWknd = isWeekend(dateObj);
                  const hasExam = dayEvents.some(
                    (e) => e.eventType === 'exam_start'
                  );
                  return (
                    <motion.div
                      key={day}
                      whileHover={{ scale: 1.02 }}
                      onClick={() => handleDateClick(day)}
                      onDoubleClick={() => handleDateDoubleClick(day)}
                      className={`min-h-[100px] p-2 rounded-lg cursor-pointer relative ${
                        isSelected
                          ? 'ring-2 ring-indigo-500 shadow-lg bg-indigo-50'
                          : isToday
                          ? 'bg-yellow-50 border-2 border-yellow-400'
                          : hasExam
                          ? 'bg-purple-50 border-2 border-purple-400'
                          : isWknd
                          ? 'bg-gray-50 border border-gray-200'
                          : 'bg-white border border-gray-200 hover:border-indigo-300'
                      }`}
                    >
                      <div className="flex items-center justify-between mb-1">
                        <span
                          className={`text-sm font-bold ${
                            isToday
                              ? 'bg-indigo-600 text-white w-7 h-7 rounded-full flex items-center justify-center'
                              : hasExam
                              ? 'text-purple-700'
                              : isWknd
                              ? 'text-gray-400'
                              : 'text-gray-700'
                          }`}
                        >
                          {day}
                          {hasExam && (
                            <span className="text-[8px] ml-0.5">📝</span>
                          )}
                        </span>
                      </div>
                      {dayEvents.slice(0, 3).map((event, idx) => {
                        const et = getEventTypeDetails(event.eventType);
                        return (
                          <div
                            key={idx}
                            className={`text-[10px] px-1.5 py-0.5 rounded-md truncate bg-gradient-to-r ${et.color} text-white mt-0.5`}
                          >
                            {event.description.substring(0, 14)}
                          </div>
                        );
                      })}
                      {dayEvents.length > 3 && (
                        <div className="text-[10px] text-gray-500 mt-1">
                          +{dayEvents.length - 3} more
                        </div>
                      )}
                    </motion.div>
                  );
                })}
              </div>
            </div>
            <div className="w-80 border-l border-gray-200 bg-gray-50 overflow-y-auto">
              <div className="p-4">
                <h3 className="text-sm font-semibold mb-3">
                  <Info size={14} className="inline mr-1" />
                  {selectedDate
                    ? formatDisplayDate(new Date(selectedDate + 'T00:00:00'))
                    : 'Select a date'}
                </h3>
                {selectedDate &&
                  selectedDateEvents.map((event, i) => {
                    const et = getEventTypeDetails(event.eventType);
                    return (
                      <div
                        key={i}
                        className={`${et.bgColor} rounded-lg p-3 border mb-2`}
                      >
                        <div className="flex items-center gap-2">
                          <et.Icon size={14} className={et.textColor} />
                          <span
                            className={`text-xs font-medium ${et.textColor}`}
                          >
                            {et.label}
                          </span>
                          {event.isAutoGenerated && (
                            <span className="text-[10px] bg-amber-100 text-amber-600 px-1 rounded">
                              Auto
                            </span>
                          )}
                          {event.isTermExam && (
                            <span className="text-[10px] bg-purple-100 text-purple-600 px-1 rounded">
                              Exam
                            </span>
                          )}
                        </div>
                        <p className="text-sm mt-1">{event.description}</p>
                        <div className="flex gap-1 mt-2">
                          <button
                            onClick={() => handleEditEvent(event)}
                            className="text-xs text-gray-500 hover:text-blue-600"
                          >
                            <Edit2 size={12} />
                          </button>
                          <button
                            onClick={() => handleDeleteEvent(event.id)}
                            className="text-xs text-gray-500 hover:text-red-600"
                          >
                            <Trash2 size={12} />
                          </button>
                        </div>
                      </div>
                    );
                  })}
              </div>
            </div>
          </div>
        )}

        {showEventModal && (
          <div className="fixed inset-0 z-[60] flex items-center justify-center print:hidden">
            <div
              className="fixed inset-0 bg-black/50"
              onClick={() => setShowEventModal(false)}
            />
            <motion.div
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              className="relative bg-white rounded-2xl shadow-xl max-w-md w-full p-6 mx-4"
            >
              <h3 className="text-lg font-bold mb-4">
                {eventForm.id ? 'Edit' : 'Add'} Event
              </h3>
              <div className="space-y-4">
                <div>
                  <label className="block text-xs font-medium mb-1">Type</label>
                  <select
                    value={eventForm.eventType}
                    onChange={(e) =>
                      setEventForm({ ...eventForm, eventType: e.target.value })
                    }
                    className="w-full rounded-lg border px-3 py-2 text-sm"
                  >
                    {EVENT_TYPES.map((et) => (
                      <option key={et.value} value={et.value}>
                        {et.label}
                      </option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="block text-xs font-medium mb-1">Date</label>
                  <input
                    type="date"
                    value={eventForm.date}
                    onChange={(e) =>
                      setEventForm({ ...eventForm, date: e.target.value })
                    }
                    className="w-full rounded-lg border px-3 py-2 text-sm"
                  />
                </div>
                <div>
                  <label className="block text-xs font-medium mb-1">
                    Description
                  </label>
                  <textarea
                    value={eventForm.description}
                    onChange={(e) =>
                      setEventForm({
                        ...eventForm,
                        description: e.target.value,
                      })
                    }
                    rows={3}
                    className="w-full rounded-lg border px-3 py-2 text-sm"
                  />
                </div>
                {eventForm.eventType === 'semester_start' &&
                  isBatchCalendar && (
                    <div className="bg-blue-50 border border-blue-200 rounded-lg p-3">
                      <p className="text-xs text-blue-700">
                        <Info size={12} className="inline mr-1" />
                        Auto-generates: Semester End (Week 16), 5 First Term
                        exams (Week 7), 5 Second Term exams (Week 12). Total: 18
                        events.
                      </p>
                    </div>
                  )}
              </div>
              <div className="flex justify-end gap-3 mt-6">
                <button
                  onClick={() => setShowEventModal(false)}
                  className="px-4 py-2 text-sm text-gray-600 hover:bg-gray-100 rounded-lg"
                >
                  Cancel
                </button>
                <button
                  onClick={handleSaveEvent}
                  disabled={saving || !eventForm.description.trim()}
                  className="px-4 py-2 text-sm bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 disabled:opacity-50 flex items-center gap-1"
                >
                  {saving ? (
                    <Loader2 size={14} className="animate-spin" />
                  ) : (
                    <Save size={14} />
                  )}
                  {eventForm.id ? 'Update' : 'Save'}
                </button>
              </div>
            </motion.div>
          </div>
        )}

        <style jsx global>{`
          @media print {
            body * {
              visibility: hidden;
            }
            .fixed.inset-0.z-50 {
              visibility: visible;
              position: absolute;
              inset: 0 !important;
            }
            .fixed.inset-0.z-50 * {
              visibility: visible;
            }
            .print\\:hidden {
              display: none !important;
            }
            .print-page {
              page-break-after: always;
              margin-bottom: 4mm;
            }
            .print-page:last-child {
              page-break-after: avoid;
            }
            @page {
              size: A4;
              margin: 6mm;
            }
          }
        `}</style>
      </motion.div>
    </div>
  );
}
