// app/api/academic-calendar/route.js
import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { prisma } from '@/lib/prisma';

// GET - Fetch calendar events
export async function GET(request) {
  try {
    const session = await getServerSession(authOptions);
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { searchParams } = new URL(request.url);
    const year = searchParams.get('year');
    const month = searchParams.get('month');
    const startDate = searchParams.get('startDate');
    const endDate = searchParams.get('endDate');
    const eventType = searchParams.get('eventType');
    const batchId = searchParams.get('batchId');
    const limit = parseInt(searchParams.get('limit') || '100');

    const where = {};

    // Filter by date range (priority over year/month)
    if (startDate && endDate) {
      const start = new Date(startDate + 'T00:00:00');
      const end = new Date(endDate + 'T23:59:59.999');
      where.date = { gte: start, lte: end };
    } else if (year) {
      const yearNum = parseInt(year);
      const monthNum = month ? parseInt(month) : null;

      if (monthNum !== null) {
        const start = new Date(yearNum, monthNum, 1);
        const end = new Date(yearNum, monthNum + 1, 0, 23, 59, 59, 999);
        where.date = { gte: start, lte: end };
      } else {
        const start = new Date(yearNum, 0, 1);
        const end = new Date(yearNum, 11, 31, 23, 59, 59, 999);
        where.date = { gte: start, lte: end };
      }
    }

    if (eventType) {
      where.eventType = eventType;
    }

    if (batchId) {
      where.batchId = parseInt(batchId);
    }

    const events = await prisma.academicCalendar.findMany({
      where,
      include: {
        batch: {
          select: { id: true, name: true },
        },
      },
      orderBy: { date: 'asc' },
      take: limit <= 0 ? 100 : Math.min(limit, 500),
    });

    return NextResponse.json({
      success: true,
      events,
      count: events.length,
    });
  } catch (error) {
    console.error('Error fetching calendar events:', error);
    return NextResponse.json(
      { error: 'Failed to fetch events', details: error.message },
      { status: 500 }
    );
  }
}

// POST - Create calendar event
export async function POST(request) {
  try {
    const session = await getServerSession(authOptions);
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json();
    console.log('Creating event with body:', body);

    const {
      date,
      eventType,
      description,
      semester,
      batchId,
      isAutoGenerated,
      isTermExam,
    } = body;

    // Validate required fields
    if (!date || !eventType || !description) {
      return NextResponse.json(
        { error: 'Date, event type, and description are required' },
        { status: 400 }
      );
    }

    // Validate event type
    const validEventTypes = [
      'semester_start',
      'semester_end',
      'holiday',
      'first_term_start',
      'first_term_end',
      'second_term_start',
      'second_term_end',
      'exam_preparation',
      'exam_start',
      'exam_end',
      'result_publication',
      'supplementary_exam',
      'college_event',
      'meeting',
      'other',
    ];

    if (!validEventTypes.includes(eventType)) {
      return NextResponse.json(
        { error: `Invalid event type: ${eventType}` },
        { status: 400 }
      );
    }

    // Parse date - handle YYYY-MM-DD format correctly
    const [year, month, day] = date.split('-').map(Number);
    if (!year || !month || !day) {
      return NextResponse.json(
        { error: 'Invalid date format. Use YYYY-MM-DD' },
        { status: 400 }
      );
    }

    const eventDate = new Date(year, month - 1, day, 12, 0, 0); // Noon to avoid timezone issues

    if (isNaN(eventDate.getTime())) {
      return NextResponse.json({ error: 'Invalid date' }, { status: 400 });
    }

    // For auto-generated events, skip duplicate check (allow multiple same events)
    if (!isAutoGenerated) {
      const existingEvent = await prisma.academicCalendar.findFirst({
        where: {
          date: eventDate,
          eventType: eventType,
          ...(batchId ? { batchId: parseInt(batchId) } : { batchId: null }),
        },
      });

      if (existingEvent) {
        return NextResponse.json(
          {
            error: `An event of type "${eventType}" already exists on this date`,
            existingEvent,
          },
          { status: 409 }
        );
      }
    }

    // Create the event
    const eventData = {
      date: eventDate,
      eventType,
      description: description.trim(),
      semester: semester || null,
      batchId: batchId ? parseInt(batchId) : null,
    };

    // Add auto-generated fields if they exist in the model
    // Check if your prisma model has these fields
    if (isAutoGenerated !== undefined) {
      eventData.isAutoGenerated = isAutoGenerated;
    }
    if (isTermExam !== undefined) {
      eventData.isTermExam = isTermExam;
    }

    console.log('Creating event with data:', eventData);

    const event = await prisma.academicCalendar.create({
      data: eventData,
      include: {
        batch: {
          select: { id: true, name: true },
        },
      },
    });

    console.log(`Created event: ${event.id} - ${event.eventType} on ${date}`);

    return NextResponse.json({
      success: true,
      message: 'Event created successfully',
      event,
    });
  } catch (error) {
    console.error('Error creating calendar event:', error);

    if (error.code === 'P2002') {
      return NextResponse.json(
        { error: 'An event already exists on this date' },
        { status: 409 }
      );
    }

    return NextResponse.json(
      { error: 'Failed to create event', details: error.message },
      { status: 500 }
    );
  }
}

// PUT - Update calendar event
export async function PUT(request) {
  try {
    const session = await getServerSession(authOptions);
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json();
    const {
      id,
      date,
      eventType,
      description,
      semester,
      batchId,
      isAutoGenerated,
      isTermExam,
    } = body;

    if (!id) {
      return NextResponse.json(
        { error: 'Event ID is required' },
        { status: 400 }
      );
    }

    const existingEvent = await prisma.academicCalendar.findUnique({
      where: { id: parseInt(id) },
    });

    if (!existingEvent) {
      return NextResponse.json({ error: 'Event not found' }, { status: 404 });
    }

    const updateData = {};

    if (date) {
      const [year, month, day] = date.split('-').map(Number);
      updateData.date = new Date(year, month - 1, day, 12, 0, 0);
    }
    if (eventType) updateData.eventType = eventType;
    if (description) updateData.description = description.trim();
    if (semester !== undefined) updateData.semester = semester || null;
    if (batchId !== undefined)
      updateData.batchId = batchId ? parseInt(batchId) : null;
    if (isAutoGenerated !== undefined)
      updateData.isAutoGenerated = isAutoGenerated;
    if (isTermExam !== undefined) updateData.isTermExam = isTermExam;

    const event = await prisma.academicCalendar.update({
      where: { id: parseInt(id) },
      data: updateData,
      include: {
        batch: { select: { id: true, name: true } },
      },
    });

    return NextResponse.json({
      success: true,
      message: 'Event updated successfully',
      event,
    });
  } catch (error) {
    console.error('Error updating calendar event:', error);
    return NextResponse.json(
      { error: 'Failed to update event', details: error.message },
      { status: 500 }
    );
  }
}

// DELETE - Remove calendar event
export async function DELETE(request) {
  try {
    const session = await getServerSession(authOptions);
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');

    if (!id) {
      return NextResponse.json(
        { error: 'Event ID is required' },
        { status: 400 }
      );
    }

    const event = await prisma.academicCalendar.findUnique({
      where: { id: parseInt(id) },
    });

    if (!event) {
      return NextResponse.json({ error: 'Event not found' }, { status: 404 });
    }

    await prisma.academicCalendar.delete({
      where: { id: parseInt(id) },
    });

    console.log(`Deleted event: ${id}`);

    return NextResponse.json({
      success: true,
      message: 'Event deleted successfully',
    });
  } catch (error) {
    console.error('Error deleting calendar event:', error);
    return NextResponse.json(
      { error: 'Failed to delete event', details: error.message },
      { status: 500 }
    );
  }
}
